title: Benedict Toh
#logo: /assets/1659262448746.jpeg
description: Welcome to my humble page where I share my passion projects in the field of Data Analytics and Data Science!
show_downloads: false
theme: jekyll-theme-minimal
