title: Benedict Toh
#logo: /assets/1659262448746.jpeg
description: Welcome to my humble page where I share my passion projects in the field of Data Analytics and Data Science!
Bachelor of Business Administration | Double Major in Business Analytics & Supply Chain Management | National University of Singapore
First Class Honours
Dean's List AY2022/2023 Semester 1
Dean's List AY2022/2023 Semester 2
Member of Beta Gamma Sigma
show_downloads: false
theme: jekyll-theme-minimal
