title: Benedict Toh
#logo: /assets/1000007052.jpg
description: Welcome to my humble page where I share my passion projects in the field of Data Analytics and Data Science! I graduated from the National University of Singapore with a Double Major in Business Analytics and Supply Chain Management and aspire to be a Data Scientist.
show_downloads: false
theme: jekyll-theme-minimal
